### ISSUE TITLE
Code Story Front Ready PoC del Front

### ISSUE THREAD

**Issue by Pabloin** [Pabloin/NinjaHack2021_CodeStory4-Apps#1]
Code Story Front Ready PoC del Front

- [x] Front en Angular
- [x] Despliegue en Docker
- [x] Subir la Imagen a la Docker Registry de IBM
- [x] Despliegue en Kubernetes en Google Cloud

Stack

- Basado en ngx-admin: Open Source Template para Angular con Licencia MIT
- Node 14.17
- Angular 10

**Comment by Pabloin** [comment]
El Front Anduvo Ok

![image](https://user-images.githubusercontent.com/21208987/120387059-d02d2280-c2ff-11eb-8342-57e3a9cd4ab4.png)

**Comment by Pabloin** [comment]
Despliegue desde Docker

```

pablo.inchausti @ My Ubuntu ~/Escritorio/_NinjaIBM_Hack/code/NinjaHack2021_CodeStory4-Apps (master)
└─ $ ▶ docker build -t pabloin/codestory-app:3.0 .
Sending build context to Docker daemon  12.16MB
Step 1/12 : FROM node:14.17.0 as build
 ---> 9153ee3e2ced
Step 2/12 : WORKDIR /app
```


**Imagen Creada a Partir del Dockerfile**

```
pablo.inchausti @ My Ubuntu ~/Escritorio/_NinjaIBM_Hack/code/NinjaHack2021_CodeStory4-Apps (master)
└─ $ ▶ docker image ls
REPOSITORY                                                                                    TAG                  IMAGE ID       CREATED              SIZE
pabloin/codestory-app                                                                         3.0                  0be3d8c863ba   About a minute ago   99.9MB


```

**Docker RUN**



```
pablo.inchausti @ My Ubuntu ~/Escritorio/_NinjaIBM_Hack/code/NinjaHack2021_CodeStory4-Apps (master)
└─ $ ▶ docker run -d  --rm -p 9999:80 pabloin/codestory-app:3.0 
1a4e7f91db92918212e155eeeb2abd5f39b5990b115fda0144eb1b99b6bb3354
```




![image](https://user-images.githubusercontent.com/21208987/120383986-f3ee6980-c2fb-11eb-8357-5b149edfe032.png)

**Comment by Pabloin** [comment]
**Subir la Imagen a IBM**

![image](https://user-images.githubusercontent.com/21208987/120391848-066da080-c306-11eb-9057-eb107c939938.png)
...
![image](https://user-images.githubusercontent.com/21208987/120391896-16858000-c306-11eb-839d-ffdca070414f.png)

Imagen Subida Ok:

![image](https://user-images.githubusercontent.com/21208987/120391994-39179900-c306-11eb-8674-db64382825b6.png)

Y en IBM Cloud Registry

![image](https://user-images.githubusercontent.com/21208987/120392279-a4fa0180-c306-11eb-9d5e-4d8be7e73421.png)

**Comment by Pabloin** [comment]
**Despliegue en Kubernetes**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      dd: web
  template:
    metadata:
      labels:
        dd: web
    spec:
      containers:
      - name: dd-site
        image: us.icr.io/pabloin/codestory-app:2.0
---
apiVersion: v1
kind: Service
metadata:
  name: dd-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    dd: web
  ports:
  - port: 4500
    targetPort: 80
    nodePort: 30003
```

Para Conectar Al Cluster

`ibmcloud ks workers -c c2pts34........etc......` 

Para Desplegar

`kubectl apply -f codestory-cloud-service-3.0.yml 
`

![image](https://user-images.githubusercontent.com/21208987/120394682-27d08b80-c30a-11eb-8647-1ce04f7f30f7.png)

Cluster de Kubernetes en la Cuenta de Code Sotry 4:

![image](https://user-images.githubusercontent.com/21208987/120395607-a4179e80-c30b-11eb-8c9c-aa3f7c67bc85.png)

**Servicios**

![image](https://user-images.githubusercontent.com/21208987/120395812-007abe00-c30c-11eb-83b8-de22544e4219.png)

Para Conocer la IP Pública del Cluster
```

ibmcloud ks cluster ls
ibmcloud ks workers -c c2pts34d..... 

```
![image](https://user-images.githubusercontent.com/21208987/120396457-f86f4e00-c30c-11eb-905b-066c4307c50d.png)

Desde el Servicio en el Cluster de Kubernetes 

La IP Publica del Cluster es:   **169.57.99.129** 

![image](https://user-images.githubusercontent.com/21208987/120396629-47b57e80-c30d-11eb-9003-2b99c282220d.png)
